ENFORCEALEXAPOLICY: true
ABSCACHEEXPIREMIN: 120
ENABLECACHE: true
REDISCACHESERVER: prod-whetstone.prgrxr.ng.0001.use1.cache.amazonaws.com
ENGINESESSIONLOGGER: Queue
ENGINESMSHANDLER: StepFunction
SMSSTEPFUNCTIONARN: arn:aws:states:us-east-1:940085449815:stateMachine:SaveMessageTestFunctions
RECORDMESSAGES: false
SESSIONAUDITQUEUE: sessionaudit
SMSOUTBOUNDQUEUE: smsoutbound
DATABASEKEY: /storyengine/prod/enginedb
TWILIOKEY: /storyengine/dev/twiliokeys
MESSAGERESENDDELAYSECONDS: 0
MESSAGERESENDRETRYLIMIT: 3
SMSSENDER: Twilio
TWILIOSTATUSCALLBACKURL: https://reeaf6p08d.execute-api.us-east-1.amazonaws.com/Prod/v1/smsmessagestatus
CLIENTMESSAGEAUDITQUEUE: clientmessages
SOURCENUMBER: +12157099492
