AWSTemplateFormatVersion: 2010-09-09
Description: Create the dynamodb user store tables
Parameters:
  EnvironmentKeyStack:
    Type: String
    Default: WhetstoneKey-Dev
    Description: Root environment stack that defines the environment key and purpose.
    AllowedPattern: '^[a-zA-Z]+[0-9a-zA-Z\-]*$'
  CustomActionLambdaStack:
    Description: >-
      Lambda utility stack. Example:
      Whetstone-LambdaCustomActions-Dev
    Type: String
    Default: Whetstone-LambdaCustomActions-Dev
  PolicyStack:
    Description: >-
      Shared policies stack. Example:
      WhetstoneSharedPolicies-Dev
    Type: String
    Default: WhetstoneSharedPolicies-Dev
  IsProduction:
    Description: Indicates whether or not production resources should be created.
    Default: false
    Type: String
    AllowedValues: [true, false]
Conditions:
  IsProd: !Equals [!Ref IsProduction, true]
Resources:
  BootstrapConfigUpdate:
    Type: 'AWS::CloudFormation::CustomResource'
    Properties:
      ServiceToken: !ImportValue
        'Fn::Sub': '${CustomActionLambdaStack}-BootstrapConfigUpdateArn'
      KeyId: !ImportValue
        'Fn::Sub': '${EnvironmentKeyStack}-EnvironmentKeyAlias'
      Parameter: !ImportValue
        'Fn::Sub': '${PolicyStack}-BootstrapParameter'
      ConfigEntries:
        - ConfigType: DynamoDbUserTable
          Value: !Ref UserTable
  UserTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: !Ref IsProduction
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'sortKey'
          AttributeType: 'S'
        - AttributeName: 'gsk1'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
        - AttributeName: 'sortKey'
          KeyType: 'RANGE'
      GlobalSecondaryIndexes:
        - IndexName: 'firstGSI'
          KeySchema:
            - AttributeName: 'gsk1'
              KeyType: 'HASH'
            - AttributeName: 'sortKey'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: ALL
      Tags:
        - Key: Environment
          Value:
            { 'Fn::ImportValue': !Sub '${EnvironmentKeyStack}-EnvironmentName' }
  UserTableAccessPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    DeletionPolicy: Delete
    Properties:
      Description: !Join
        - ''
        - - 'Used in the '
          - !ImportValue
            'Fn::Sub': '${EnvironmentKeyStack}-EnvironmentName'
          - ' environment to read from and write to the DynamoDB user table store'
      Path: !Join
        - ''
        - - /
          - !ImportValue
            'Fn::Sub': '${EnvironmentKeyStack}-EnvironmentName'
          - /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'dynamodb:PutItem'
              - 'dynamodb:DeleteItem'
              - 'dynamodb:GetItem'
              - 'dynamodb:Query'
              - 'dynamodb:UpdateItem'
              - 'dynamodb:DescribeTable'
              - 'dynamodb:BatchWriteItem'
            Resource: !GetAtt UserTable.Arn
          - Effect: Allow
            Action:
              - 'dynamodb:PutItem'
              - 'dynamodb:DeleteItem'
              - 'dynamodb:GetItem'
              - 'dynamodb:Query'
              - 'dynamodb:UpdateItem'
              - 'dynamodb:DescribeTable'
              - 'dynamodb:BatchWriteItem'
            Resource: !Join
              - /
              - - !GetAtt UserTable.Arn
                - index/firstGSI
  UserTableStreamPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    DeletionPolicy: Delete
    Properties:
      Description: !Join
        - ''
        - - 'Used in the '
          - !ImportValue
            'Fn::Sub': '${EnvironmentKeyStack}-EnvironmentName'
          - ' environment access the user table DynamoDB stream from a lambda that handles write propagation to the PostgreSQL backing store'
      Path: !Join
        - ''
        - - /
          - !ImportValue
            'Fn::Sub': '${EnvironmentKeyStack}-EnvironmentName'
          - /
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'dynamodb:UpdateItem'
              - 'dynamodb:DescribeTable'
              - 'dynamodb:DescribeStream'
              - 'dynamodb:GetRecords'
              - 'dynamodb:GetShardIterator'
              - 'dynamodb:ListStreams'
            Resource: !GetAtt UserTable.StreamArn
          - Effect: Allow
            Action:
              - 'dynamodb:UpdateItem'
              - 'dynamodb:DescribeTable'
            Resource: !GetAtt UserTable.Arn
Outputs:
  UserTableArn:
    Description: DynamoDb User Table Arn
    Value: !GetAtt UserTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-UserTableArn'
  UserTableName:
    Description: DynamoDb User Table Name
    Value: !Ref UserTable
    Export:
      Name: !Sub '${AWS::StackName}-UserTableName'
  UserTableStreamArn:
    Description: DynamoDB User Table Stream Arn
    Value: !GetAtt UserTable.StreamArn
    Export:
      Name: !Sub '${AWS::StackName}-UserTableStreamArn'
  UserTableAccessPolicy:
    Description: DynamoDb User Access PolicyDocument
    Value: !Ref UserTableAccessPolicy
    Export:
      Name: !Sub '${AWS::StackName}-UserTableAccessPolicyArn'
  UserTableStreamPolicy:
    Description: DynamoDb policy for use by lambda the reads the user table dynamo db stream.
    Value: !Ref UserTableStreamPolicy
    Export:
      Name: !Sub '${AWS::StackName}-UserTableStreamPolicyArn'
