using System;
using System.Collections.Generic;
using System.Text;
using Newtonsoft.Json;

namespace Whetstone.StoryEngine.Reporting.Models
{

    /// <summary>
    /// This defines message that is generated by the report generator task and sent to the
    /// report dispatcher.
    /// </summary>
    public class ReportSendStatus
    {


        /// <summary>
        /// Paths to the report files to send.
        /// </summary>
        [JsonProperty(PropertyName = "outputFiles")]
        public List<FileSendStatus> OutputFiles { get; set; }


        /// <summary>
        /// Defines the destination to send the reports to.
        /// </summary>
        [JsonProperty(PropertyName = "destination")]
        public ReportDestinationBase Destination { get; set; }

        [JsonProperty(PropertyName = "allSent")]
        public bool AllSent { get; set; }



        [JsonProperty(PropertyName = "sendAttempts")]
        public int SendAttempts { get; set; }

    }



    public class FileSendStatus
    {

        [JsonProperty(PropertyName = "filePath")]
        public string FilePath { get; set; }

        [JsonProperty(PropertyName = "isSent")]
        public bool IsSent { get; set; }


    }
}
